Repository meilisearch/meilisearch-ruby, pull requests merged in 2020-10, with the labels that each got.

#92 Add code-samples
  .code-samples.meilisearch.yaml
Labels: Hacktoberfest

#94 Update tests for MeiliSearch v0.15.0
  spec/meilisearch/index/search_spec.rb
Labels: skip-changelog

#97 Enable all Rubocop rules
  .rubocop.yml
  lib/meilisearch/error.rb
Labels: Hacktoberfest, skip-changelog

#105 New README
  README.md
Labels: skip-changelog
