Repository meilisearch/meilisearch-ruby, pull requests merged in 2022-10, with the labels that each got.

#366 Update version for the next release (v0.20.0)
  lib/meilisearch/version.rb
Labels: breaking-change

#371 chores: replace MEILISEARCH_HOST with MEILISEARCH_URL
  docker-compose.yml
  spec/spec_helper.rb
Labels: enhancement, skip-changelog

#373 Update to checkout@v3 and remove warning
  .github/workflows/tests.yml
Labels: skip-changelog

#384 Add new code-samples for matching_strategy
  .code-samples.meilisearch.yaml
Labels: documentation
