Repository meilisearch/meilisearch-ruby, pull requests merged in 2022-07, with the labels that each got.

#330 Update HTTP methods
  lib/meilisearch/index.rb
Labels: breaking-change

#343 Update version for the next release (v0.19.0)
  lib/meilisearch/version.rb
Labels: skip-changelog

#347 Replace MeiliSearch by Meilisearch
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/pre-release-tests.yml
  .github/workflows/tests.yml
Labels: skip-changelog

#349 Add nbHits to keep backwards compatibility
  .rubocop_todo.yml
  lib/meilisearch/index.rb
  spec/meilisearch/index/search/q_spec.rb
  spec/spec_helper.rb
Labels: breaking-change

#351 Update version for the next release (v0.19.1)
  lib/meilisearch/version.rb
Labels: skip-changelog

#352 Add faceting settings customization
  .rubocop_todo.yml
  lib/meilisearch/index.rb
  spec/meilisearch/index/settings_spec.rb
Labels: enhancement
