Repository meilisearch/meilisearch-ruby, pull requests merged in 2024-05, with the labels that each got.

#533 Remove ruby 3.0 & Upgrade codecov setup
  .github/workflows/pre-release-tests.yml
  .github/workflows/tests.yml
  Gemfile
  bors.toml
  docker-compose.yml
  spec/spec_helper.rb
Labels: breaking-change

#534 Clarify the ruby version
  README.md
Labels: documentation

#536 fix delete documents by filter documentation
  .code-samples.meilisearch.yaml
Labels: documentation, skip-changelog
