Repository meilisearch/meilisearch-ruby, pull requests merged in 2024-02, with the labels that each got.

#516 Drop support for ruby 2 and add ruby 3.2 to CI
  .github/workflows/gempush.yml
  .github/workflows/pre-release-tests.yml
  .github/workflows/tests.yml
  .rubocop.yml
  README.md
  bors.toml
  lib/meilisearch/utils.rb
  meilisearch.gemspec
  spec/spec_helper.rb
Labels: breaking-change, maintenance

#521 Fix ruby specs
  spec/meilisearch/index/search/attributes_to_highlight_spec.rb
  spec/meilisearch/index/search/show_ranking_score_details_spec.rb
Labels: maintenance

#498 Implement new await synchronous interface
  .rubocop_todo.yml
  lib/meilisearch.rb
  lib/meilisearch/client.rb
  lib/meilisearch/index.rb
  lib/meilisearch/models/task.rb
  lib/meilisearch/utils.rb
  spec/meilisearch/client/dumps_spec.rb
  spec/meilisearch/client/indexes_spec.rb
  spec/meilisearch/client/multi_search_spec.rb
  spec/meilisearch/client/requests_spec.rb
  spec/meilisearch/client/tasks_spec.rb
  spec/meilisearch/client/token_spec.rb
  spec/meilisearch/index/base_spec.rb
  spec/meilisearch/index/documents_spec.rb
  spec/meilisearch/index/search/attributes_to_crop_spec.rb
  spec/meilisearch/index/search/facets_distribution_spec.rb
  spec/meilisearch/index/search/filter_spec.rb
  spec/meilisearch/index/search/multi_params_spec.rb
  spec/meilisearch/index/search/nested_fields_spec.rb
  spec/meilisearch/index/search/offset_spec.rb
  spec/meilisearch/index/search/q_spec.rb
  spec/meilisearch/index/search/sort_spec.rb
  spec/meilisearch/index/search/vector_search.rb
  spec/meilisearch/index/settings_spec.rb
  spec/meilisearch/models/task_spec.rb
  spec/meilisearch/utils_spec.rb
  spec/spec_helper.rb
  spec/support/books_contexts.rb
  spec/support/task_helpers.rb
Labels: enhancement
