Repository meilisearch/meilisearch-ruby, pull requests merged in 2025-02, with the labels that each got.

#567 Federated search added
  .code-samples.meilisearch.yaml
  lib/meilisearch/multi_search.rb
  spec/meilisearch/client/multi_search_spec.rb
Labels: enhancement

#601 Update httparty
  meilisearch.gemspec
Labels: maintenance

#599 Support batching and updating with JSON, NDJSON, and CSV
  .rubocop_todo.yml
  lib/meilisearch/http_request.rb
  lib/meilisearch/index.rb
  spec/meilisearch/index/documents_spec.rb
Labels: enhancement

#604 Update version for next release (v0.31.0)
  lib/meilisearch/version.rb
Labels: skip-changelog
